export const QueryName = {
    FIND_MESSAGES: 'FIND_MESSAGES',
    FIND_MESSAGE: 'FIND_MESSAGE',
    GET_USER: 'GET_USER',
    PROFILE: 'PROFILE',
    LIKES: 'LIKES',
    FAVORITES: 'FAVORITES',
    MY_FAVORITES: 'MY_FAVORITES',
    AVATAR_DOWNLOAD: 'AVATAR_DOWNLOAD',
} as const;

export const MESSAGES_LIMIT = 10;
